### PR TITLE
Support History on REPL

### PR DESCRIPTION
**Pull request by amiremohamadi**
support hitory on REPL, so the user does not have to retype again and again the same things, but can use down/up arrows in order to search and re-edit already inserted lines of text.

### CODE REVIEW

**Comment by amiremohamadi** [comment]
also it would be nice to remove Cargo.lock from `.gitignore`, as rust documents encourage to commit `Cargo.lock` into repository [[link]](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)

**Comment by amiremohamadi** [comment]
all in all, I really liked the idea and syntax! really creative and fun. appreciate your efforts :beers:

**Comment by amiremohamadi** [comment]
it would be fun to add its benchmarks on your other repo ([language_performance_prime_algorithm]( https://github.com/ali77gh/language_performance_prime_algorithm)) and see the results :D

**Comment by ali77gh** [comment]
> support hitory on REPL, so the user does not have to retype again and again the same things, but can use down/up arrows in order to search and re-edit already inserted lines of text.

Thanks a lot for your contribution. left and right cursor movement is also fixed.

**Comment by ali77gh** [comment]
> also it would be nice to remove Cargo.lock from `.gitignore`, as rust documents encourage to commit `Cargo.lock` into repository [[link]](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)

bdfe2b376c4cb0be019c12a9e6eec23f9f369011 fixed

**Comment by ali77gh** [comment]
> it would be fun to add its benchmarks on your other repo ([language_performance_prime_algorithm](https://github.com/ali77gh/language_performance_prime_algorithm)) and see the results :D

Chap is added: [link](https://github.com/ali77gh/language_performance_prime_algorithm#my-laptop-intelr-coretm-i7-8550u)
Its 12 times slower than python.

There are many performance Issues in chap and i'm planning performance improvement for 3.0.0 after my [2.0.0 TODOs](https://github.com/ali77gh/chap#todos)

**Pull request merged**
